Importação de CSV

In [60]:
import pandas as pd

csv = pd.read_csv("../data/customers.csv", sep=";")

#Número de colunas
len(csv.columns)

#Número de linhas
len(csv.index)

#Todos os UUIDs como Serie
csv.UUID

#Shape com valores RowsxColumns numa tupla
csv.shape

(791, 3)

Condicionais básicas no Pandas

In [61]:

maxPoints = csv["Points"].max()
conditionMax = csv["Points"] == maxPoints

condition = csv["Points"] > 2000

conditionMore1000Less2000 =  (csv["Points"] >= 1000) & (csv["Points"] < 2000)
df_1000_2000 = csv[conditionMore1000Less2000].copy()

#Manipulando uma cópia dos dados para não mexer direto na referencia
df_1000_2000["Points"] = df_1000_2000["Points"] + 1000

csv[condition]
csv[conditionMax]
df_1000_2000

                                     UUID                 Name  Points
1    2d3d2dce-d353-4961-ad39-46723efe2100        mariicmartins    2375
26   54edd84d-73ad-4821-8d53-7ed04f00b2e4          kaycristina    2153
29   a1478518-6bf1-41e7-895b-355a06554b96          talismacedo    2116
34   99431a0f-1f38-47ab-9136-445c7afae00d       nicolaslima167    2364
43   af4f97a5-90a8-4ebf-8420-d7766ad093ea            ldbressan    2038
47   4c77c153-19b9-42e2-a03c-04f43dcc6105      vinnyportugal07    2211
59   21943df7-272e-46ef-aeb7-933a6637bfd5          gabra_alves    2013
60   2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1          dabathehutt    2307
68   74c06e4d-0d4f-48f1-96af-a03c7b18ce47           thamibetin    2940
77   98953b1a-ae7e-4e50-b264-bdda6c3a4a6d          ericcamacho    2423
99   8151fff4-0b51-4577-ae0b-4622d244d324            neelister    2214
126  803debdb-8136-4cb5-af29-dcd8db36bf2c             lucasnv_    2173
139  ce61fa42-2854-42d4-b20d-e9348e9d76e1            chicovivo    2324
149  9c909d1e-fa2a-47b0-8535-d9e44375f9f8           marcos_oap    2213
156  8cf8e162-bcf1-4a68-9ea5-44ec75484734              reis131    2247
178  161bf8aa-33f9-42a3-b48f-97199c8370d1             zackwild    2146
200  10d18590-4365-465c-8174-311c38d3a548           telbatesbr    2026
203  7be4584b-288b-4027-a2fe-29d206313917               censeu    2301
273  9c49a075-02a6-4a14-bc38-7b3bf18aa723  patriciasilvarecife    2100
274  5ed09fff-c0eb-48db-b6e3-20ef238e8b5c     gustavolourenco_    2287
379  ce0f9a00-3862-40ee-84bc-1aba65c19e15              edbruxo    2400
418  d6f92668-964e-462c-93e9-25e7771a5852            eduard0ml    2144
450  52e4293d-0b9c-4215-be0d-e0d63e3536b3             nicosp90    2828
496  7107771a-0558-4aaa-a66e-570205a7f367              leogend    2607
497  3f55b86f-dc21-4ac8-8e89-7c1535359eaf         tapioca_amin    2394
507  24ef9aed-ab90-41bf-bf90-88d17210d1b2          thiagolange    2263
532  87040a44-0e04-4cc1-ad91-072d167b11b1       inimigodomouse    2606
735  f39b1da2-7633-4d8f-99b4-6ffd1e0f0d23      gleicearaujo_ds    2204

Ordenação

In [62]:
csv = (csv.sort_values( by=["Points", "Name"],
                      ascending=[False, True] )
        .rename(columns={"Name":"Nome", "Points":"Pontos"}))

csv

                                     UUID             Nome  Pontos
436  066c9fc6-f704-4165-a8f3-3d1968b0d4a3         marxzera    4304
120  9aba2685-7c0a-4d1f-8e22-0c47ca0af580     itsevolution    4262
3    65662aff-44d6-4f06-b9d9-07445c6e5943           kozat0    4063
122  46119557-7ce9-488f-9225-47d539dd414e         kallklen    2272
118  3bd342b6-e5ff-456b-b8e7-8aabbe9f0a32  unbiaseddestiny    2210
..                                    ...              ...     ...
444  21038105-6ffd-45f1-bcf3-19feb6ba48f8         xlkurama       0
545  9cea717d-9edf-4740-a06d-41597784da46         xstrdoto       0
668  1990522f-6994-44ea-8a30-0115f1f4c6c1         yarinha7       0
286  bef9264e-1e65-44ec-a56e-3127b77b121e        yohminato       0
447  f04eeeea-7b30-4aca-88f8-2bf94c1e6e9a          yuse1br       0

[791 rows x 3 columns]

Renomeando Colunas

In [63]:
csv.rename(columns={
    "Name": "Nome", 
    "Points": "Pontos"
})

                                     UUID             Nome  Pontos
436  066c9fc6-f704-4165-a8f3-3d1968b0d4a3         marxzera    4304
120  9aba2685-7c0a-4d1f-8e22-0c47ca0af580     itsevolution    4262
3    65662aff-44d6-4f06-b9d9-07445c6e5943           kozat0    4063
122  46119557-7ce9-488f-9225-47d539dd414e         kallklen    2272
118  3bd342b6-e5ff-456b-b8e7-8aabbe9f0a32  unbiaseddestiny    2210
..                                    ...              ...     ...
444  21038105-6ffd-45f1-bcf3-19feb6ba48f8         xlkurama       0
545  9cea717d-9edf-4740-a06d-41597784da46         xstrdoto       0
668  1990522f-6994-44ea-8a30-0115f1f4c6c1         yarinha7       0
286  bef9264e-1e65-44ec-a56e-3127b77b121e        yohminato       0
447  f04eeeea-7b30-4aca-88f8-2bf94c1e6e9a          yuse1br       0

[791 rows x 3 columns]